### ISSUE TITLE
Mismatch in release name

### ISSUE THREAD

**Issue by nisrulz** [SmartToolFactory/Compose-BeforeAfter#24]
<img width="378" alt="Screenshot 2024-09-12 at 11 27 03" src="https://github.com/user-attachments/assets/ad028d62-6e17-41aa-bebe-bb1706c8319b">

Just noticed there is some mismatch in the actual release name.

<img width="381" alt="Screenshot 2024-09-12 at 11 28 15" src="https://github.com/user-attachments/assets/544f63a7-ac43-4853-a709-63098fe2b72a">
<img width="453" alt="Screenshot 2024-09-12 at 11 28 20" src="https://github.com/user-attachments/assets/f55bc2a6-4c74-4520-bdf9-a4ae54fc36b2">

It should be `v1.1.0` in the release section.

**Comment by SmartToolFactory** [comment]
Thanks for pointing out and for your amazing contributions to this library. Update name to match with latest version.
