### ISSUE TITLE
Release v1.1.1

### ISSUE THREAD

**Issue by nisrulz** [SmartToolFactory/Compose-BeforeAfter#36]
- With recent changes, could a release be made?
> I would like to use the new changes for the Slider move callbacks.

Additionally, a Question: 

Would it make sense that the library itself can be released when merged to `master` as in a new tag + release will be made automatically via Github Actions?

- Maybe all future PRs goto a develop and only when a PR from develop to master is made, is when the Github Action to make a tag and release would be triggered. It can also be configured to be manually triggered on demand rather than automatically. [Something like this](https://github.com/marketplace/actions/create-tag-release).

Your thoughts?

**Comment by SmartToolFactory** [comment]
Sure, i will create a release now. That would be awesome. I'm also interested in migrating libraries to KMP, add static code analysis with detect or maybe with Spotless, never used this one before, and as you suggested creating branches and CI/CD. These are awesome suggestions by the way.

**Comment by nisrulz** [comment]
I'll close this issue for now. I will create another issue to discuss possible approaches to enhancing this library.
