### ISSUE TITLE
[Proposal] Be added as a maintainer in this repo

### ISSUE THREAD

**Issue by nisrulz** [SmartToolFactory/Compose-BeforeAfter#73]
Hi, 

This is just a proposal. 

I would like to help with maintaining this project. I see the PRs are pilling up and maybe I can help with reviewing, merging and releasing the changes.

I am not looking for full write permissions, but any restricted ones to help support you and this project.

Obviously I would adhere to the code of conduct as well as make sure all changes are done via a PR only. This just acts as a safety net that you can always revert anything that was merged.

Additionally, I would also request you to set up branch rules for your `main` branch to never allow for any pushes but everything needs to be added via a PR. 

You can do that in your Settings > Branches > Add rule set.

<img width="507" alt="Screenshot 2024-12-12 at 10 03 24" src="https://github.com/user-attachments/assets/851b2de9-b237-4405-8d1a-107dbb1fd849" />
<img width="774" alt="Screenshot 2024-12-12 at 10 03 38" src="https://github.com/user-attachments/assets/9bd1a824-7116-44ea-84bb-c8990a3c39c5" />

Side Note: If this is not something you would want, then there is nothing to do. Simple close this issue 😄 

Thank you for creating this project!

**Comment by SmartToolFactory** [comment]
Hi @nisrulz , thank you a lot for your contributions. I sent you collaborator invitations. Also created ruleset as you requested. I'm sorry i'm currently busy with work and i'm working on some particle explosion/disintegration library i got stuck with something. If you have any suggestions always feel free to open an issue. 

Regards,

Fatih

**Comment by nisrulz** [comment]
Thank you so much!

I totally understand the situation and this is why decided to lend you a hand. Happy to contribute.

I would be looking at the open PRs for now and making sure everything works before merging them.

Closing this issue now.
